apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lz6febrkh-go 
  janus-idp.io/tekton: lz6febrkh-go
  backstage.io/kubernetes-id: lz6febrkh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lz6febrkh-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  